"""Add org_id to users table for data permissions

Revision ID: 004_add_org_id
Revises: 3666a9a9ed2a
Create Date: 2026-02-28 18:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004_add_org_id'
down_revision: Union[str, Sequence[str], None] = '3666a9a9ed2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: Add org_id column to users table for data permissions."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('org_id', sa.Integer(), nullable=True, comment='组织 ID（用于数据权限过滤）')
        )
        batch_op.create_index('ix_users_org_id', ['org_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: Remove org_id column from users table."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_org_id')
        batch_op.drop_column('org_id')
    
    # ### end Alembic commands ###
