"""Create role_permissions table for dynamic permission matrix

Revision ID: 005_create_role_permissions
Revises: 004_add_org_id
Create Date: 2026-02-28 18:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005_create_role_permissions'
down_revision: Union[str, Sequence[str], None] = '004_add_org_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: Create role_permissions table for dynamic permission matrix."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False, comment='角色名称'),
        sa.Column('resource', sa.String(length=50), nullable=False, comment='资源名称（customer, settlement, report, user, role）'),
        sa.Column('action', sa.String(length=20), nullable=False, comment='操作类型（create, read, update, delete, view）'),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('role', 'resource', 'action', name='uq_role_resource_action')
    )
    
    # 创建索引加速权限查询
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index('ix_role_permissions_role', ['role'], unique=False)
        batch_op.create_index('ix_role_permissions_resource', ['resource'], unique=False)
    
    # 预置权限数据（4 级 RBAC 默认权限矩阵）
    preset_permissions = [
        # Admin: ALL permissions for all resources
        ('admin', 'customer', 'create'),
        ('admin', 'customer', 'read'),
        ('admin', 'customer', 'update'),
        ('admin', 'customer', 'delete'),
        ('admin', 'settlement', 'create'),
        ('admin', 'settlement', 'read'),
        ('admin', 'settlement', 'update'),
        ('admin', 'settlement', 'delete'),
        ('admin', 'report', 'view'),
        ('admin', 'report', 'export'),
        ('admin', 'user', 'create'),
        ('admin', 'user', 'read'),
        ('admin', 'user', 'update'),
        ('admin', 'user', 'delete'),
        ('admin', 'role', 'create'),
        ('admin', 'role', 'read'),
        ('admin', 'role', 'update'),
        ('admin', 'role', 'delete'),
        
        # 经理 (Manager): All business functions except role management
        ('manager', 'customer', 'create'),
        ('manager', 'customer', 'read'),
        ('manager', 'customer', 'update'),
        ('manager', 'customer', 'delete'),
        ('manager', 'settlement', 'create'),
        ('manager', 'settlement', 'read'),
        ('manager', 'settlement', 'update'),
        ('manager', 'settlement', 'delete'),
        ('manager', 'report', 'view'),
        ('manager', 'report', 'export'),
        ('manager', 'user', 'read'),
        ('manager', 'user', 'update'),  # Can update user role
        
        # 专员 (Specialist): Customer management and settlement processing
        ('specialist', 'customer', 'create'),
        ('specialist', 'customer', 'read'),
        ('specialist', 'customer', 'update'),
        ('specialist', 'customer', 'delete'),
        ('specialist', 'settlement', 'read'),
        ('specialist', 'report', 'view'),
        ('specialist', 'user', 'read'),
        
        # 销售 (Sales): Only customer read and create
        ('sales', 'customer', 'create'),
        ('sales', 'customer', 'read'),
    ]
    
    # 批量插入预设数据
    conn = op.get_bind()
    for role, resource, action in preset_permissions:
        conn.execute(
            sa.text('INSERT INTO role_permissions (role, resource, action) VALUES (:role, :resource, :action)'),
            {"role": role, "resource": resource, "action": action}
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: Drop role_permissions table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permissions')
    # ### end Alembic commands ###
