"""Create organizations and customers tables for data permission testing

Revision ID: 006_create_orgs_and_customers
Revises: 005_create_role_permissions
Create Date: 2026-03-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006_create_orgs_and_customers'
down_revision: Union[str, Sequence[str], None] = '005_create_role_permissions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: Create organizations and customers tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create organizations table
    op.create_table(
        'organizations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False, comment='组织名称'),
        sa.Column('code', sa.String(length=50), nullable=False, comment='组织代码（用于系统间同步）'),
        sa.Column('parent_id', sa.Integer(), nullable=True, comment='父组织 ID（支持组织层级）'),
        sa.Column('status', sa.String(length=20), nullable=False, default='active', comment='组织状态（active/inactive）'),
        sa.Column('description', sa.String(length=500), nullable=True, comment='组织描述'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['parent_id'], ['organizations.id'], ),
    )
    op.create_index('ix_organizations_name', 'organizations', ['name'], unique=False)
    op.create_index('ix_organizations_code', 'organizations', ['code'], unique=True)
    
    # Create customers table
    op.create_table(
        'customers',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False, comment='客户名称（公司名称）'),
        sa.Column('contact_name', sa.String(length=100), nullable=False, comment='联系人姓名'),
        sa.Column('contact_email', sa.String(length=200), nullable=True, comment='联系人邮箱'),
        sa.Column('contact_phone', sa.String(length=50), nullable=True, comment='联系人电话'),
        sa.Column('address', sa.Text(), nullable=True, comment='客户地址'),
        sa.Column('sales_rep_id', sa.Integer(), nullable=False, comment='销售代表 ID（数据权限过滤）'),
        sa.Column('org_id', sa.Integer(), nullable=False, comment='组织 ID（数据权限过滤）'),
        sa.Column('status', sa.String(length=20), nullable=False, default='active', comment='客户状态（active/inactive/lead）'),
        sa.Column('notes', sa.Text(), nullable=True, comment='备注信息'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['sales_rep_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    )
    op.create_index('ix_customers_name', 'customers', ['name'], unique=False)
    op.create_index('ix_customers_sales_rep_id', 'customers', ['sales_rep_id'], unique=False)
    op.create_index('ix_customers_org_id', 'customers', ['org_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: Drop customers and organizations tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop customers table
    op.drop_index('ix_customers_org_id', table_name='customers')
    op.drop_index('ix_customers_sales_rep_id', table_name='customers')
    op.drop_index('ix_customers_name', table_name='customers')
    op.drop_table('customers')
    
    # Drop organizations table
    op.drop_index('ix_organizations_code', table_name='organizations')
    op.drop_index('ix_organizations_name', table_name='organizations')
    op.drop_table('organizations')
    
    # ### end Alembic commands ###
