"""Create users table

Revision ID: 3666a9a9ed2a
Revises: 
Create Date: 2026-02-27 03:50:43.497070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3666a9a9ed2a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名（唯一）'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='bcrypt 加密的密码哈希'),
    sa.Column('real_name', sa.String(length=100), nullable=False, comment='真实姓名'),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'SPECIALIST', 'SALES', name='userrole'), nullable=False, comment='用户角色（4 级 RBAC）'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱地址'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号码'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'LOCKED', name='userstatus'), nullable=False, comment='用户状态'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True, comment='最后登录 IP'),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False, comment='连续登录失败次数'),
    sa.Column('locked_until', sa.DateTime(), nullable=True, comment='锁定截止时间（防暴力破解）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
