"""add_permission_audit_logs_table

Revision ID: 710228662a7a
Revises: 008
Create Date: 2026-03-01 22:46:39.411114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710228662a7a'
down_revision: Union[str, Sequence[str], None] = '008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False, comment='用户 ID'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('resource', sa.String(length=100), nullable=False, comment='资源名称'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作类型'),
    sa.Column('ip_address', sa.String(length=45), nullable=False, comment='IP 地址'),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False, comment='是否异常访问'),
    sa.Column('anomaly_type', sa.String(length=50), nullable=True, comment='异常类型'),
    sa.Column('details', sa.Text(), nullable=True, comment='详细信息（JSON 格式）'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='操作时间'),
    sa.CheckConstraint("anomaly_type IN ('unauthorized_access', 'frequent_access', 'location_anomaly', 'privilege_escalation')", name='chk_anomaly_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permission_audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_resource_action', ['resource', 'action'], unique=False)
        batch_op.create_index('idx_audit_user_timestamp', ['user_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_audit_logs_anomaly_type'), ['anomaly_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_audit_logs_is_anomaly'), ['is_anomaly'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_audit_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('permission_matrix', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               comment='角色名称',
               existing_nullable=False)
        batch_op.alter_column('module',
               existing_type=sa.VARCHAR(length=100),
               comment='功能模块',
               existing_nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=20),
               comment='操作类型',
               existing_nullable=False)
        batch_op.alter_column('granted',
               existing_type=sa.BOOLEAN(),
               comment='是否授权',
               existing_nullable=False)

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=20),
               comment='操作类型（create, read, update, delete, view, export）',
               existing_comment='操作类型（create, read, update, delete, view）',
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_role_permissions_is_additional'))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               comment='角色名称',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               comment='角色描述',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态',
               existing_nullable=False)
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               comment='角色层级（数字越大权限越高）',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('parent_role_id',
               existing_type=sa.INTEGER(),
               comment='父角色 ID（用于权限继承）',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_roles_level'))
        batch_op.drop_index(batch_op.f('idx_roles_parent_role_id'))
        batch_op.drop_constraint(batch_op.f('fk_roles_parent_role'), type_='foreignkey')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_org_id'))
        batch_op.drop_column('org_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='组织 ID（用于数据权限过滤）'))
        batch_op.create_index(batch_op.f('ix_users_org_id'), ['org_id'], unique=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_roles_parent_role'), 'roles', ['parent_role_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_roles_parent_role_id'), ['parent_role_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_roles_level'), ['level'], unique=False)
        batch_op.alter_column('parent_role_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='父角色 ID（用于权限继承）',
               existing_nullable=True)
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='角色层级（数字越大权限越高）',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='状态',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='角色描述',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='角色名称',
               existing_nullable=False)

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_role_permissions_is_additional'), ['is_additional'], unique=False)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=20),
               comment='操作类型（create, read, update, delete, view）',
               existing_comment='操作类型（create, read, update, delete, view, export）',
               existing_nullable=False)

    with op.batch_alter_table('permission_matrix', schema=None) as batch_op:
        batch_op.alter_column('granted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否授权',
               existing_nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='操作类型',
               existing_nullable=False)
        batch_op.alter_column('module',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='功能模块',
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='角色名称',
               existing_nullable=False)

    with op.batch_alter_table('permission_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_permission_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_permission_audit_logs_is_anomaly'))
        batch_op.drop_index(batch_op.f('ix_permission_audit_logs_anomaly_type'))
        batch_op.drop_index('idx_audit_user_timestamp')
        batch_op.drop_index('idx_audit_resource_action')

    op.drop_table('permission_audit_logs')
    # ### end Alembic commands ###
